# Generated by Django 3.2.23 on 2024-01-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='imgaes/')),
                ('personalExperience', models.TextField(blank=True, null=True)),
                ('locations', models.ManyToManyField(to='locations.Location')),
                ('services', models.ManyToManyField(to='services.Service')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
