# Generated by Django 4.2.7 on 2024-04-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
