# Generated by Django 3.2.23 on 2024-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_practitioner_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
